import Link from "next/link";
import AdminShell from "@/components/AdminShell";
import VariantForm from "@/components/VariantForm";
import {prisma} from "@/lib/prisma";
import {requirePagePermission} from "@/lib/authz";
import {can} from "@/lib/permissions";
export default async function NewVariant({searchParams}:{searchParams:Promise<{model?:string;source?:string;mode?:string;q?:string;page?:string}>}){
 const user=await requirePagePermission("products.create");const sp=await searchParams;const source=sp.source?await prisma.product.findUnique({where:{id:sp.source},include:{images:{orderBy:{sortOrder:"asc"}},productModel:true}}):null;
 const modelId=sp.model??source?.productModelId;const model=modelId?await prisma.productModel.findUnique({where:{id:modelId},include:{brand:true}}):null;
 const mode=sp.mode==="color"||sp.mode==="size"||sp.mode==="duplicate"?sp.mode:"new";
 const page=Math.max(1,Math.min(100000,parseInt(sp.page??"1")||1));const query=(sp.q??"").slice(0,100);
 const models=model?[model]:await prisma.productModel.findMany({where:{active:true,...(query?{OR:[{code:{contains:query,mode:"insensitive" as const}},{name:{contains:query,mode:"insensitive" as const}},{brand:{name:{contains:query,mode:"insensitive" as const}}}]}:{})},include:{brand:true},take:30,skip:(page-1)*30,orderBy:[{code:"asc"},{id:"asc"}]});
 const label=mode==="color"?"Ajouter un coloris":mode==="size"?"Ajouter une taille":mode==="duplicate"?"Dupliquer l’article":"Ajouter un article";
 return <AdminShell active="/admin/articles"><Link href="/admin/articles" className="text-sm text-stone">← Articles</Link><h1 className="my-6 text-3xl font-semibold">{label}</h1>{model?<><p className="mb-5 text-sm text-stone">{model.brand.name} · {model.code} · {model.name}</p><div className="max-w-5xl"><VariantForm product={source} model={model} models={models} user={user} mode={mode}/></div></>:<><p className="mb-5 text-sm text-stone">Choisissez le modèle de cette variante.{source&&!source.productModelId?" Cet ancien article n’est pas encore rattaché à un modèle. Ses données resteront conservées.":""}</p><form className="mb-5 flex flex-wrap gap-3"><input name="q" defaultValue={query} aria-label="Rechercher un modèle" placeholder="Rechercher un modèle" className="min-h-11 rounded-lg border bg-white px-3 text-sm"/>{sp.source&&<input type="hidden" name="source" value={sp.source}/>}<input type="hidden" name="mode" value={mode}/><button className="rounded-lg bg-ink px-4 text-white">Rechercher</button>{can(user,"models.create")&&<Link className="rounded-lg border bg-white px-4 py-3 text-sm" href="/admin/modeles/nouveau">Créer un modèle</Link>}</form><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{models.map(m=><Link key={m.id} href={`/admin/produits/nouveau?model=${m.id}&mode=${mode}${sp.source?`&source=${sp.source}`:""}`} className="rounded-xl border bg-white p-5 hover:border-red"><p className="text-xs text-stone">{m.brand.name}</p><p className="mt-2 font-semibold">{m.code}</p><p className="mt-1 text-sm">{m.name}</p></Link>)}</div>{models.length===0&&<p className="text-sm text-stone">Aucun modèle disponible. Créez un modèle pour commencer.</p>}<div className="mt-5 flex gap-5 text-sm">{page>1&&<Link href={`?page=${page-1}&q=${encodeURIComponent(query)}&mode=${mode}${sp.source?`&source=${sp.source}`:""}`}>Précédent</Link>}{models.length===30&&<Link href={`?page=${page+1}&q=${encodeURIComponent(query)}&mode=${mode}${sp.source?`&source=${sp.source}`:""}`}>Suivant</Link>}</div></>}</AdminShell>;
}

