import Link from "next/link";
import AdminShell from "@/components/AdminShell";
import { requirePagePermission } from "@/lib/authz";
import { getAddressDirectory } from "@/lib/address-directory";
import { createDelegationAction, createGovernorateAction, createLocalityAction, updateDelegationAction, updateGovernorateAction, updateLocalityAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function AddressDirectoryPage({ searchParams }: { searchParams: Promise<{ governorate?: string; delegation?: string }> }) {
  const session = await requirePagePermission("settings.manage");
  const [directory, query] = await Promise.all([getAddressDirectory(), searchParams]);
  const governorate = directory.find((entry) => entry.id === query.governorate) ?? directory[0];
  const delegation = governorate?.delegations.find((entry) => entry.id === query.delegation) ?? governorate?.delegations[0];
  const href = (governorateId: string, delegationId?: string) => `/admin/adresses?governorate=${encodeURIComponent(governorateId)}${delegationId ? `&delegation=${encodeURIComponent(delegationId)}` : ""}`;

  return <AdminShell active="/admin/adresses" name={session?.name} email={session?.email} role={session?.role}>
    <p className="eyebrow text-red">Checkout</p><h1 className="font-display mt-2 text-3xl">Référentiel des adresses</h1>
    <p className="mt-2 max-w-3xl text-sm text-stone">Les choix proposés aux clients sont gérés ici. Toute nouvelle commande utilise ces données ; les anciennes commandes gardent leur adresse enregistrée.</p>
    <div className="mt-7 grid gap-5 xl:grid-cols-[280px_310px_minmax(0,1fr)]">
      <section className="rounded-2xl border border-line bg-white p-4"><h2 className="font-semibold">Gouvernorats</h2><div className="mt-3 grid gap-2">{directory.map((entry) => <Link key={entry.id} href={href(entry.id)} className={`rounded-lg px-3 py-2 text-sm ${entry.id === governorate?.id ? "bg-red text-white" : "hover:bg-mist"}`}>{entry.name}</Link>)}</div><form action={createGovernorateAction} className="mt-4 flex gap-2"><input name="name" required placeholder="Nouveau gouvernorat" className="min-w-0 flex-1 rounded-lg border border-line px-2 text-xs"/><button className="rounded-lg bg-red px-3 text-xs font-semibold text-white">Ajouter</button></form></section>
      <section className="rounded-2xl border border-line bg-white p-4"><h2 className="font-semibold">Délégations</h2>{governorate && <form action={updateGovernorateAction.bind(null, governorate.id)} className="mt-3 flex gap-2"><input name="name" defaultValue={governorate.name} className="min-w-0 flex-1 rounded-lg border border-line px-2 py-1.5 text-xs"/><button className="rounded-lg border border-line px-2 text-xs">Modifier</button></form>}<div className="mt-3 grid gap-2">{governorate?.delegations.map((entry) => <Link key={entry.id} href={href(governorate.id, entry.id)} className={`rounded-lg px-3 py-2 text-sm ${entry.id === delegation?.id ? "bg-red text-white" : "hover:bg-mist"}`}>{entry.name}</Link>)}</div>{governorate && <form action={createDelegationAction} className="mt-4 flex gap-2"><input type="hidden" name="governorateId" value={governorate.id}/><input name="name" required placeholder="Nouvelle délégation" className="min-w-0 flex-1 rounded-lg border border-line px-2 text-xs"/><button className="rounded-lg bg-red px-3 text-xs font-semibold text-white">Ajouter</button></form>}</section>
      <section className="rounded-2xl border border-line bg-white p-4"><h2 className="font-semibold">Localités</h2>{delegation && <><form action={updateDelegationAction.bind(null, delegation.id)} className="mt-3 flex gap-2"><input name="name" defaultValue={delegation.name} className="min-w-0 flex-1 rounded-lg border border-line px-2 py-1.5 text-xs"/><button className="rounded-lg border border-line px-2 text-xs">Modifier</button></form><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[440px] text-sm"><thead className="text-left text-xs text-stone"><tr><th className="pb-2">Localité</th><th className="pb-2">Code postal</th><th/></tr></thead><tbody>{delegation.localities.map((entry) => <tr key={entry.id} className="border-t border-line"><td colSpan={3} className="py-2"><form action={updateLocalityAction.bind(null, entry.id)} className="grid grid-cols-[minmax(0,1fr)_110px_auto] gap-2"><input name="name" defaultValue={entry.name} className="min-w-0 rounded-lg border border-line px-2 py-1.5 text-sm"/><input name="postalCode" defaultValue={entry.postalCode ?? ""} placeholder="Code postal" className="rounded-lg border border-line px-2 py-1.5 text-sm"/><button className="rounded-lg border border-line px-3 text-xs hover:border-red hover:text-red">Enregistrer</button></form></td></tr>)}</tbody></table></div><form action={createLocalityAction} className="mt-4 grid gap-2 sm:grid-cols-[minmax(0,1fr)_120px_auto]"><input type="hidden" name="delegationId" value={delegation.id}/><input name="name" required placeholder="Nouvelle localité" className="rounded-lg border border-line px-3 py-2 text-sm"/><input name="postalCode" placeholder="Code postal" className="rounded-lg border border-line px-3 py-2 text-sm"/><button className="rounded-lg bg-red px-4 py-2 text-sm font-semibold text-white">Ajouter</button></form></>}</section>
    </div>
  </AdminShell>;
}
