import Link from "next/link";
import { AlertTriangle, Boxes, CircleOff, PackageSearch, Search } from "lucide-react";
import AdminShell from "@/components/AdminShell";
import StockQuantityControl from "@/components/StockQuantityControl";
import ManagedImage from "@/components/ManagedImage";
import { prisma } from "@/lib/prisma";
import { requirePagePermission } from "@/lib/authz";
import { can } from "@/lib/permissions";
import { updateStockAction } from "../catalogue-actions";

type StockFilter = "in-stock" | "low" | "out" | undefined;
const PAGE_SIZE = 30;
const stateFor = (stock: number | null, threshold: number) => stock === null ? { label: "Non suivi", className: "bg-slate-500/10 text-slate-500" } : stock === 0 ? { label: "Rupture", className: "bg-red/10 text-red" } : stock <= threshold ? { label: "Stock faible", className: "bg-amber-500/15 text-amber-700" } : { label: "En stock", className: "bg-emerald-500/15 text-emerald-700" };
function href(q: string, stock?: StockFilter, page = 1) { const p = new URLSearchParams(); if (q) p.set("q", q); if (stock) p.set("stock", stock); if (page > 1) p.set("page", String(page)); return p.size ? `?${p}` : "?"; }

export default async function Stocks({ searchParams }: { searchParams: Promise<{ q?: string; page?: string; stock?: string }> }) {
  const user = await requirePagePermission("stock.view");
  const { q: sourceQuery = "", page = "1", stock: sourceStock } = await searchParams;
  const q = sourceQuery.trim().slice(0, 100);
  const stock: StockFilter = sourceStock === "in-stock" || sourceStock === "low" || sourceStock === "out" ? sourceStock : undefined;
  const current = Math.max(1, Math.min(100000, parseInt(page) || 1));
  const settings = await prisma.storeSettings.findUnique({ where: { singletonKey: "main" }, select: { lowStockThreshold: true } });
  const threshold = settings?.lowStockThreshold ?? 5;
  const base = { archived: false };
  const search = q ? { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { reference: { contains: q, mode: "insensitive" as const } }, { variantReference: { contains: q, mode: "insensitive" as const } }, { brand: { name: { contains: q, mode: "insensitive" as const } } }, { productModel: { is: { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { code: { contains: q, mode: "insensitive" as const } }] } } }] } : {};
  const stockWhere = stock === "in-stock" ? { stock: { gt: threshold } } : stock === "low" ? { stock: { gt: 0, lte: threshold } } : stock === "out" ? { stock: 0 } : {};
  const [rows, inStock, low, out, totals] = await Promise.all([
    prisma.product.findMany({ where: { ...base, ...search, ...stockWhere }, orderBy: [{ stock: "asc" }, { id: "asc" }], take: PAGE_SIZE, skip: (current - 1) * PAGE_SIZE, select: { id: true, name: true, reference: true, stock: true, size: true, frameColorLabel: true, brand: { select: { name: true } }, productModel: { select: { code: true, name: true } }, images: { take: 1, orderBy: { sortOrder: "asc" }, select: { url: true } } } }),
    prisma.product.count({ where: { ...base, stock: { gt: threshold } } }), prisma.product.count({ where: { ...base, stock: { gt: 0, lte: threshold } } }), prisma.product.count({ where: { ...base, stock: 0 } }), prisma.product.aggregate({ where: base, _sum: { stock: true } }),
  ]);
  const filters: { key?: StockFilter; label: string; count?: number }[] = [{ label: "Tous" }, { key: "in-stock", label: "En stock", count: inStock }, { key: "low", label: "Stock faible", count: low }, { key: "out", label: "Rupture", count: out }];
  const stats = [{ label: "Articles en stock", value: inStock, icon: Boxes, color: "text-emerald-500" }, { label: "Stock faible", value: low, icon: AlertTriangle, color: "text-amber-500" }, { label: "Ruptures", value: out, icon: CircleOff, color: "text-red" }, { label: "Quantité totale", value: totals._sum.stock ?? 0, icon: PackageSearch, color: "text-violet-500" }];
  const article = (product: typeof rows[number]) => <><strong className="block truncate">{product.brand.name} {product.productModel?.name ?? product.name}</strong><small className="block truncate text-stone">{[product.productModel?.code, product.frameColorLabel, product.size].filter(Boolean).join(" · ")}</small></>;
  const image = (product: typeof rows[number]) => <span className="relative grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-lg bg-mist">{product.images[0]?.url ? <ManagedImage src={product.images[0].url} alt="" fill sizes="48px" className="object-contain"/> : <PackageSearch size={18} className="text-stone"/>}</span>;
  return <AdminShell active="/admin/stocks"><header><p className="eyebrow text-red">Catalogue</p><h1 className="mt-2 text-3xl font-semibold">Stocks</h1><p className="mt-2 text-sm text-stone">Gestion du stock global des articles · seuil faible : ≤ {threshold}.</p></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, icon: Icon, color }) => <div key={label} className="flex items-center gap-3 rounded-xl border border-line bg-white p-4"><span className={`grid h-10 w-10 place-items-center rounded-lg bg-mist ${color}`}><Icon size={19}/></span><div><p className="text-xl font-semibold tabular-nums">{value}</p><p className="text-xs text-stone">{label}</p></div></div>)}</section>
    <section className="mt-6 rounded-xl border border-line bg-white p-3 sm:p-4"><form className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search size={17} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-stone"/><input name="q" defaultValue={q} placeholder="Rechercher par nom, modèle, référence ou marque" aria-label="Rechercher un article" className="min-h-11 w-full rounded-lg border border-line bg-mist/35 pl-10 pr-3 text-sm outline-none transition focus:border-red focus:bg-white"/></label><button className="min-h-11 rounded-lg bg-ink px-5 text-sm font-semibold text-white">Rechercher</button></form><nav aria-label="Filtrer les stocks" className="mt-3 flex flex-wrap gap-2">{filters.map((filter) => <Link key={filter.label} href={href(q, filter.key)} className={`rounded-full border px-3 py-1.5 text-xs font-medium transition ${stock === filter.key ? "border-red bg-red text-white" : "border-line text-stone hover:border-red hover:text-red"}`}>{filter.label}{filter.count !== undefined && <span className="ml-1.5 opacity-75">{filter.count}</span>}</Link>)}</nav></section>
    <section className="mt-5 overflow-hidden rounded-xl border border-line bg-white"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-mist/70 text-xs uppercase tracking-wide text-stone"><tr><th className="px-5 py-3 font-medium">Article</th><th className="px-4 py-3 font-medium">Référence</th><th className="px-4 py-3 font-medium">État</th><th className="px-4 py-3 text-right font-medium">Quantité</th><th className="px-5 py-3 text-right font-medium">Action</th></tr></thead><tbody className="divide-y divide-line">{rows.map((product) => { const state = stateFor(product.stock, threshold); return <tr key={product.id} className="transition hover:bg-mist/40"><td className="px-5 py-3"><Link href={`/admin/produits/${product.id}`} className="flex items-center gap-3">{image(product)}<span className="min-w-0">{article(product)}</span></Link></td><td className="px-4 py-3 font-mono text-xs text-stone">{product.reference}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${state.className}`}>{state.label}</span></td><td className="px-4 py-3 text-right font-semibold tabular-nums">{product.stock ?? "—"}</td><td className="px-5 py-3">{can(user, "stock.edit") ? <StockQuantityControl action={updateStockAction.bind(null, product.id)} value={product.stock}/> : <span className="text-xs text-stone">Consultation</span>}</td></tr>; })}</tbody></table></div><div className="grid gap-3 p-3 md:hidden">{rows.map((product) => { const state = stateFor(product.stock, threshold); return <article key={product.id} className="rounded-xl border border-line bg-mist/30 p-3"><div className="flex gap-3">{image(product)}<Link href={`/admin/produits/${product.id}`} className="min-w-0 flex-1">{article(product)}<p className="mt-1 truncate font-mono text-xs text-stone">{product.reference}</p></Link><span className={`h-fit rounded-full px-2 py-1 text-[11px] font-semibold ${state.className}`}>{state.label}</span></div><div className="mt-3 flex items-center justify-between gap-3 border-t border-line pt-3"><span className="text-sm">Quantité <strong className="ml-1 tabular-nums">{product.stock ?? "—"}</strong></span>{can(user, "stock.edit") && <StockQuantityControl action={updateStockAction.bind(null, product.id)} value={product.stock}/>}</div></article>; })}</div>{rows.length === 0 && <p className="p-10 text-center text-sm text-stone">Aucun article ne correspond à cette recherche.</p>}</section>
    <nav aria-label="Pagination des stocks" className="mt-5 flex items-center justify-between text-sm">{current > 1 ? <Link href={href(q, stock, current - 1)} className="admin-action-button">← Précédent</Link> : <span/>}{rows.length === PAGE_SIZE && <Link href={href(q, stock, current + 1)} className="admin-action-button">Suivant →</Link>}</nav>
  </AdminShell>;
}
