import ManagedImage from "@/components/ManagedImage";
import Link from "next/link";
import type { Prisma } from "@prisma/client";
import { ArrowUpRight, ChevronDown } from "lucide-react";
import { formatDT } from "@/lib/currency";
import { colorSwatch, commercialSizeFor } from "@/lib/catalogue-options";
type DetailedProduct = Prisma.ProductGetPayload<{ include: { brand:true; productModel:true; images:true } }>;
const colorOf=(variant:DetailedProduct)=>variant.frameColorFamily ?? variant.color ?? variant.frameColorLabel ?? "";
const isPurchasable=(variant:DetailedProduct)=>variant.available&&(variant.stock==null||variant.stock>0);

export default function ProductVariantOptions({current,variants,showPrices}:{current:DetailedProduct;variants:DetailedProduct[];showPrices:boolean}){
 const selectedColor=colorOf(current); const sameColor=variants.filter((variant)=>colorOf(variant)===selectedColor); const sizes=[...new Map(sameColor.filter((variant)=>variant.size).map((variant)=>[variant.size!,variant])).values()];
 const otherColors=[...new Map(variants.filter((variant)=>colorOf(variant)&&colorOf(variant)!==selectedColor).map((variant)=>[colorOf(variant),variant])).values()]; const model=current.productModel; const selectedSize=current.size??"Standard"; const selectedSizeName=current.commercialSize||(current.size?commercialSizeFor(current.size):"Standard");
 return <section className="mt-7 border-y border-black/15" aria-label="Tailles et coloris"><div className="py-5"><div className="flex flex-wrap items-center gap-x-5 gap-y-3"><p className="text-sm font-semibold">Taille sélectionnée</p><div className="flex flex-wrap gap-2" aria-label={`Tailles disponibles en ${selectedColor}`}>
 {sizes.length?sizes.map((variant)=>{const selected=variant.id===current.id;const content=<><strong className="block text-sm">{variant.commercialSize||commercialSizeFor(variant.size!)||"Standard"}</strong><span className="block text-xs">{variant.size}</span></>;const style=`grid min-h-10 min-w-20 place-items-center rounded-md border-2 px-3 py-1 text-center leading-tight ${selected?"border-black bg-white":"border-black/15 bg-[#fafafa] hover:border-black"}`;return isPurchasable(variant)||selected?<Link key={variant.id} href={`/produit/${variant.slug}`} aria-current={selected?"page":undefined} className={style}>{content}</Link>:<span key={variant.id} aria-disabled="true" className={`${style} cursor-not-allowed opacity-45`}>{content}</span>; }):<span className="grid min-h-10 min-w-20 place-items-center rounded-md border-2 border-black bg-white px-3 py-1 text-center leading-tight"><strong className="block text-sm">{selectedSizeName}</strong><span className="block text-xs">{selectedSize}</span></span>}</div><Link href="/guide" className="group inline-flex min-h-10 items-center gap-2 text-sm font-semibold underline decoration-black/25 underline-offset-4 hover:decoration-black"><span className="grid h-7 w-7 place-items-center rounded-full border border-black/55 group-hover:bg-black group-hover:text-white"><ArrowUpRight size={16}/></span>Guide des tailles</Link></div>
 {selectedColor&&<div className="mt-5 flex flex-wrap items-center gap-3 border-t border-black/10 pt-5"><p className="text-sm font-semibold">Couleur sélectionnée</p><span className="inline-flex min-h-10 items-center gap-2 rounded-md border border-black/15 bg-[#fafafa] px-3 text-sm font-medium"><span className="h-4 w-4 rounded-full border border-black/15" style={{background:colorSwatch(selectedColor)}}/>{selectedColor}</span>{current.frameColorLabel&&current.frameColorLabel!==selectedColor&&<span className="text-sm text-black/55">{current.frameColorLabel}</span>}</div>}</div>
 {otherColors.length>0&&<details className="group/colors border-t border-black/10"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-4 py-3 [&::-webkit-details-marker]:hidden"><span className="text-sm font-semibold">Autres coloris disponibles</span><span className="ml-auto inline-flex items-center gap-2 rounded-md border border-black/20 px-3 py-2 text-xs"><span className="h-4 w-4 rounded-full border border-black/10 bg-[conic-gradient(#ef4444,#f59e0b,#22c55e,#3b82f6,#a855f7,#ef4444)]"/>{otherColors.length} coloris <ChevronDown size={15} className="transition group-open/colors:rotate-180"/></span></summary><div className="grid gap-2 border-t border-black/10 py-4 sm:grid-cols-2">{otherColors.map((variant)=>{const available=isPurchasable(variant); const color=colorOf(variant); const content=<><span className="relative h-16 overflow-hidden bg-[#f4f4f4]">{variant.images[0]?<ManagedImage src={variant.images[0].url} alt={variant.images[0].alt??variant.name} fill quality={90} sizes="76px" className="object-contain"/>:<span className="absolute inset-0 m-auto h-7 w-7 rounded-full" style={{background:colorSwatch(color)}}/>}</span><span className="min-w-0"><span className={`block text-[11px] font-medium ${available?"text-emerald-700":"text-stone"}`}>{available?variant.stock===1?"1 paire en stock":"En stock":"Indisponible"}</span><strong className="mt-1 block truncate text-sm">{model?.code} {variant.variantReference} {variant.size}</strong><span className="mt-1 flex items-center gap-2 text-xs text-black/60"><span className="h-3.5 w-3.5 rounded-full border border-black/15" style={{background:colorSwatch(color)}}/>{color}</span></span>{showPrices&&<strong className="whitespace-nowrap text-sm">{Number(variant.price)>0?formatDT(Number(variant.price)):"En boutique"}</strong>}</>; return available?<Link key={variant.id} href={`/produit/${variant.slug}`} className="group grid grid-cols-[76px_minmax(0,1fr)_auto] items-center gap-3 border border-black/10 p-2 hover:border-black hover:bg-[#fafafa]">{content}</Link>:<div key={variant.id} aria-disabled="true" className="grid grid-cols-[76px_minmax(0,1fr)_auto] items-center gap-3 border border-black/10 bg-[#fafafa] p-2 opacity-65">{content}</div>;})}</div></details>}</section>;
}
