"use client";
import { useMemo, useState } from "react";
import { COMMERCIAL_SIZES, FRAME_COLORS, FRAME_SIZES, LENS_COLORS, TEMPLE_LENGTHS, commercialSizeFor, type ColorOption } from "@/lib/catalogue-options";

function ColorPicker({ title, familyName, labelName, options, initialFamily, initialLabel, dark }: { title:string; familyName:string; labelName:string; options:ColorOption[]; initialFamily?:string|null; initialLabel?:string|null; dark?:boolean }) {
  const all = useMemo(() => initialFamily && !options.some((option) => option.label === initialFamily) ? [{ label: initialFamily, swatch: "#d1d5db" }, ...options] : options, [initialFamily, options]);
  const [selected, setSelected] = useState(initialFamily ?? ""); const current = all.find((option) => option.label === selected); const field = `min-h-11 w-full rounded-lg border px-3 text-sm ${dark ? "border-slate-700 bg-slate-900 text-slate-100" : "border-line bg-white"}`;
  return <fieldset className={`grid gap-3 rounded-xl border p-4 ${dark ? "border-slate-700 bg-[#0b1522]" : "border-line"}`}><legend className="px-2 text-sm font-semibold">{title}</legend><label className="grid gap-1.5 text-sm font-semibold">Couleur standard<span className="flex items-center gap-3"><span className="h-8 w-8 shrink-0 rounded-full border border-black/15" style={{background:current?.swatch ?? "#fff"}}/><select className={field} name={familyName} value={selected} onChange={(event)=>setSelected(event.target.value)} required><option value="">Choisir une couleur</option>{all.map((option)=><option key={option.label} value={option.label}>{option.label}</option>)}</select></span></label><label className="grid gap-1.5 text-sm font-semibold">Coloris exact fabricant <span className="font-normal opacity-70">(facultatif)</span><input className={field} name={labelName} defaultValue={initialLabel ?? ""} maxLength={80} placeholder="Ex. Old Gold"/></label></fieldset>;
}

export default function VariantAttributeSelectors({ initialSize, initialFrameColorFamily, initialFrameColorLabel, initialLensColorFamily, initialLensColorLabel, dark=false }: { initialSize?:string|null; initialFrameColorFamily?:string|null; initialFrameColorLabel?:string|null; initialLensColorFamily?:string|null; initialLensColorLabel?:string|null; dark?:boolean }) {
  const parts=initialSize?.split("-") ?? []; const initialBase=parts.length>=2?`${parts[0]}-${parts[1]}`:""; const isInitialCustom=Boolean(initialBase&&!FRAME_SIZES.includes(initialBase as typeof FRAME_SIZES[number]));
  const [baseSize,setBaseSize]=useState(isInitialCustom?"__custom":initialBase); const [customSize,setCustomSize]=useState(isInitialCustom?initialSize??"":""); const [temple,setTemple]=useState(isInitialCustom?"":parts[2]??""); const [commercialSize,setCommercialSize]=useState(initialSize?commercialSizeFor(initialSize):"");
  const manual=baseSize==="__custom"; const size=manual?customSize.trim():[baseSize,temple].filter(Boolean).join("-"); const sizeParts=size.split("-"); const field=`min-h-11 w-full rounded-lg border px-3 text-sm ${dark?"border-slate-700 bg-slate-900 text-slate-100":"border-line bg-white"}`;
  return <section className="grid gap-4" aria-label="Taille et couleurs"><fieldset className={`rounded-xl border p-4 ${dark?"border-slate-700 bg-[#0b1522]":"border-line"}`}><legend className="px-2 text-sm font-semibold">Taille et dimensions</legend><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-semibold">Taille verre / pont<select className={field} value={baseSize} onChange={(event)=>setBaseSize(event.target.value)} required><option value="">Choisir une taille</option>{FRAME_SIZES.map((value)=><option key={value} value={value}>{value} · {commercialSizeFor(value)}</option>)}<option value="__custom">Autre taille…</option></select></label>{manual?<label className="grid gap-1.5 text-sm font-semibold">Taille personnalisée<input className={field} value={customSize} onChange={(event)=>setCustomSize(event.target.value)} required placeholder="Ex. 53-21-145"/></label>:<label className="grid gap-1.5 text-sm font-semibold">Longueur de branche<select className={field} value={temple} onChange={(event)=>setTemple(event.target.value)}><option value="">Non renseignée</option>{TEMPLE_LENGTHS.map((value)=><option key={value} value={value}>{value} mm</option>)}</select></label>}</div><label className="mt-4 grid max-w-sm gap-1.5 text-sm font-semibold">Taille commerciale<select className={field} name="commercialSize" value={commercialSize} onChange={(event)=>setCommercialSize(event.target.value)}><option value="">Automatique ({commercialSizeFor(size)||"—"})</option>{COMMERCIAL_SIZES.map((value)=><option key={value} value={value}>{value}</option>)}</select></label><p className={`mt-3 min-h-5 text-sm ${dark?"text-slate-300":"text-stone"}`}>{sizeParts[0]&&sizeParts[1]?<>Dimensions enregistrées automatiquement : <strong className={dark?"text-white":"text-ink"}>verre {sizeParts[0]} mm · pont {sizeParts[1]} mm{sizeParts[2]?` · branche ${sizeParts[2]} mm`:""}</strong></>:"Choisissez une taille ou saisissez une mesure personnalisée."}</p><input type="hidden" name="size" value={size}/></fieldset><div className="grid gap-4 lg:grid-cols-2"><ColorPicker title="Couleur monture" familyName="frameColorFamily" labelName="frameColorLabel" options={FRAME_COLORS} initialFamily={initialFrameColorFamily} initialLabel={initialFrameColorLabel} dark={dark}/><ColorPicker title="Couleur verre" familyName="lensColorFamily" labelName="lensColorLabel" options={LENS_COLORS} initialFamily={initialLensColorFamily} initialLabel={initialLensColorLabel} dark={dark}/></div></section>;
}
